# This environment is meant to be used on local development
# computers without a dedicated GPU for machine learning.
# It does not install the PyTorch CUDA toolkit.
#
# Usage: Install with "conda env create -f environment-cpu.yml"
#        Update with  "conda env update -f environment-cpu.yml"
#        Remove with  "conda env remove --name cs231n"
#
#        Activate the environment with "conda activate cs231n"
#        Deactivate with "conda deactivate"
#
# To install conda itself, head to this URL:
# https://docs.conda.io/en/latest/miniconda.html
name: cs269q
channels:
  - defaults
dependencies:
  - python=3.7
  - numpy
  - scipy
  - jupyter
  - tqdm
  - pip
  - pip:
    - pyquil